name = "defacto-client"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
pages_build_output_dir = ".next"
# Add this for the main client build

[env.production.vars]
EXCLUDE_ADMIN = "true"
NEXT_PUBLIC_DOMAIN = "https://defactoapp.com.ng"
NEXT_PUBLIC_BASE_URL = "https://api.defactoapp.com.ng/api/v1"
NEXT_PUBLIC_TEST_USER_EMAIL = "kats.com.ng@gmail.com"
NEXT_PUBLIC_TEST_PASSWORD = "123456"
NEXT_PUBLIC_TEST_USERNAME = "Decafato user"
NEXT_PUBLIC_TEST_PHONE_NUMBER = "08063145125"
NEXT_PUBLIC_RESTRICT_LAT = 9.082
NEXT_PUBLIC_RESTRICT_LONG = 8.6753

# The FLUTTER_WAVE_KEY and GOOGLE API keys should be added as secrets
# These should be managed through the wrangler secrets commands:

# To add secrets via wrangler command line:
# $ wrangler secret put FLUTTER_WAVE_KEY
# $ wrangler secret put NEXT_PUBLIC_GOOGLE_API_KEY
# $ wrangler secret put NEXT_PUBLIC_GOOGLE_MAPS_API_KEY

# Alternatively, add them via the Cloudflare dashboard if required.

