import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google";
import "./../globals.css";
import {cn} from "@/lib/utils";
import {Button} from "@/components/ui/button";
import PropTypes from 'prop-types';
import {AdminFooter, AdminHeader} from "@/app/admin/components/admin.header";
import Head from "next/head";
import { ToastContainer, toast } from 'react-toastify';
import React from "react";
import 'react-toastify/dist/ReactToastify.css';

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});
export const metadata: Metadata = {
    title: "Defacto Administrator",
    description: "Generated by create next app",
};

export default function AdminRootLayout({
                                            children,
                                        }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en" suppressHydrationWarning>
        <Head>
            <title>Defacto Administrator</title>
            <meta name="description" content="Generated by create next app"/>
        </Head>
        <body
            className={cn(
                "bg-background font-sans antialiased",
                fontSans.variable,
            )}
        >

        <AdminHeader/>
        <ToastContainer position="top-center"/>
        {children}

        <div>

            <AdminFooter/>
        </div>
        </body>
        </html>
    );
}


export const runtime = 'edge';