import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google";
import "./../globals.css";
import {cn} from "@/lib/utils";
import {Button} from "@/components/ui/button";
import PropTypes from 'prop-types';
import {AdminFooter, AdminHeader} from "@/app/admin/components/admin.header";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Defacto Administrator",
    description: "Generated by create next app",
};

export default function AdminRootLayout({
                                            children,
                                        }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={cn(
                "bg-background font-sans antialiased",
                fontSans.variable,
            )}
        >

        <AdminHeader/>

        {children}

        <div>

            <AdminFooter/>
        </div>
        </body>
        </html>
    );
}


export const runtime = 'edge';