import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import PropTypes from "prop-types";
import Link from "next/link";
import { UserRoundCog, ArrowBigDown } from "lucide-react";
import env from "@/config/env";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <Header />

        {children}

        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}

RootLayout.propType = {
  children: PropTypes.node,
  layout: PropTypes.string,
};
