import Header from "@/components/Header";
import "../app/globals.css";
import Footer from "@/components/Footer";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}</body>
        <Footer/>
    </html>
  )
}
