// data.ts
export const restaurants = [
  {
    id: '1',
    name: 'Cold Stone Creamery',
    rating: 4.5,
    time: '5-20 mins',
    category: 'Salad',
    image: '/rest/cold.jpg',
    background: '/rest/cold.jpg',
    distance: '2.8KM',
    fee: '$2.00',
    hours: '8am-9pm, Monday to Saturday',
    products: [
      { id: '1', name: 'Mixed Vegetable Salad', price: '₦5,000' },
      { id: '2', name: 'Fruit & Spice Salad', price: '₦5,000' },
    ],
  },
  {
    id: '2',
    name: 'Mr.Biggs',
    rating: 4.5,
    time: '5-20 mins',
    category: 'Salad',
    image: '/rest/biggs.jpg',
    background: '/rest/biggs.jpg',
    distance: '2.8KM',
    fee: '$2.00',
    hours: '8am-9pm, Monday to Saturday',
    products: [
      { id: '1', name: 'Mixed Vegetable Salad', price: '₦5,000' },
      { id: '2', name: 'Fruit & Spice Salad', price: '₦5,000' },
    ],
  },
  {
    id: '3',
    name: 'Chicken Republic',
    rating: 4.5,
    time: '5-20 mins',
    category: 'Salad',
    image: '/rest/chickenrep.jpg',
    background: '/rest/chickenrep.jpg',
    distance: '2.8KM',
    fee: '$2.00',
    hours: '8am-9pm, Monday to Saturday',
    products: [
      { id: '1', name: 'Mixed Vegetable Salad', price: '₦5,000' },
      { id: '2', name: 'Fruit & Spice Salad', price: '₦5,000' },
    ],
  },
  {
    id: '4',
    name: 'KFC',
    rating: 4.5,
    time: '5-20 mins',
    category: 'Salad',
    image: '/rest/kfc1.jpg',
    background: '/rest/kfc1.jpg',
    distance: '2.8KM',
    fee: '$2.00',
    hours: '8am-9pm, Monday to Saturday',
    products: [
      { id: '1', name: 'Mixed Vegetable Salad', price: '₦5,000' },
      { id: '2', name: 'Fruit & Spice Salad', price: '₦5,000' },
    ],
  },
  {
    id: '5',
    name: 'Dominos Pizza',
    rating: 4.5,
    time: '5-20 mins',
    category: 'Salad',
    image: '/rest/domino.jpg',
    background: '/rest/domino.jpg',
    distance: '2.8KM',
    fee: '$2.00',
    hours: '8am-9pm, Monday to Saturday',
    products: [
      { id: '1', name: 'Mixed Vegetable Salad', price: '₦5,000' },
      { id: '2', name: 'Fruit & Spice Salad', price: '₦5,000' },
    ],
  },
  {
    id: '6',
    name: 'Chef Burgers London',
    rating: 4.5,
    time: '5-20 mins',
    category: 'Salad',
    image: '/rest/kfc1.jpg',
    background: '/rest/kfc1.jpg',
    distance: '2.8KM',
    fee: '$2.00',
    hours: '8am-9pm, Monday to Saturday',
    products: [
      { id: '1', name: 'Mixed Vegetable Salad', price: '₦5,000' },
      { id: '2', name: 'Fruit & Spice Salad', price: '₦5,000' },
    ],
  },
];
