name: Deploy Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: "root" # Replace with your server's username
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Deploy User Application
            cd /var/www/defacto/web/user
            git fetch --force origin main
            git reset --hard origin/main
            git pull origin main
            npx jsonbank-env dev .env force
            rm -rf node_modules
            npm install --production
            pm2 restart user_app
            
            # Deploy Admin Application
            cd /var/www/defacto/web/admin
            git fetch --force origin main
            git reset --hard origin/main
            git pull origin main
            npx jsonbank-env dev .env force
            rm -rf node_modules
            npm install --production
            pm2 restart admin_app
